parent = "customized"

recipes = [
    # Prepares Debian for booting on a Raspberry Pi.
    "core/rpi-debian-setup",
    # Install Memfault configuration.
    "memfaultd-config",
]

[parameters.memfaultd-config]
device_type = "rpi5"
