parent = "customized"

recipes = [
    # Setup Debian for booting via Grub.
    "core/debian-grub-setup",
    # Install Memfault configuration.
    "memfaultd-config",
]

[parameters.memfaultd-configure]
device_type = "efi"
