parent = "core/debian-bookworm"

recipes = [
    # Set a static hostname.
    "core/set-hostname",
    # Setup and enable SSH.
    "core/ssh",
    # Enable system discovery in the local network.
    "rugix-extra/avahi",
    # Setup network and time synchronization.
    "rugix-extra/debian-setup-network",
    "rugix-extra/debian-setup-timesyncd",
    # Install dev SSH keys from `.env` file.
    "rugix-extra/dev-local-ssh-keys",
    # Auto commit to the currently booted version.
    "rugix-extra/rugix-systemd-auto-commit",
    # Install a static web page.
    "hello-world",
    # Install Memfault.
    "memfaultd",
    # Install the Memfault Rugix OTA update service.
    "memfault-ota-rugix",
]

[parameters."core/set-hostname"]
hostname = "rugix-template-memfault"
