parent = "customized"

recipes = [
    # Prepares Debian for booting on a Raspberry Pi.
    "core/rpi-debian-setup",
    # Install Memfault configuration.
    "memfaultd-configure",
]

[parameters.memfaultd-configure]
device_type = "rpi5"
